### ISSUE TITLE
Dockerhub image out of date

### ISSUE THREAD

**Issue by nhova** [captainGeech42/ransomwatch#51]
Running the Dockerhub image results in 

app_1    | Traceback (most recent call last):
app_1    |   File "/app/ransomwatch.py", line 98, in <module>
app_1    |     NotificationManager.send_error_notification(f"Non-scraping failure", tb, fatal=True)
app_1    |   File "/app/notifications/manager.py", line 30, in send_error_notification
app_1    |     for workspace, params in Config["slack"].items():
app_1    | KeyError: 'slack'

Works if the image is built

**Comment by captainGeech42** [comment]
Yikes, thank you @nhova ! I will get an updated image pushed.

**Comment by captainGeech42** [comment]
A new image has been published from `main`.
